#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MySportsBook.Resource", IsApplication=true)]

namespace MySportsBook
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int month_array = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int ColorPrimary = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ColorPrimaryDark = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int accent = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int actionbarbackground = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int background_Color = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int labeltext_Color = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int login_password_color = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int login_username_color = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int menu_drawer_background = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int menu_drawer_margin_line = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int menu_drawer_textcolor = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int menudrawer_sidemenu_name_background = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06009f
			public const int _100sdp = 2131099807;
			
			// aapt resource value: 0x7f0600a0
			public const int _101sdp = 2131099808;
			
			// aapt resource value: 0x7f0600a1
			public const int _102sdp = 2131099809;
			
			// aapt resource value: 0x7f0600a2
			public const int _103sdp = 2131099810;
			
			// aapt resource value: 0x7f0600a3
			public const int _104sdp = 2131099811;
			
			// aapt resource value: 0x7f0600a4
			public const int _105sdp = 2131099812;
			
			// aapt resource value: 0x7f0600a5
			public const int _106sdp = 2131099813;
			
			// aapt resource value: 0x7f0600a6
			public const int _107sdp = 2131099814;
			
			// aapt resource value: 0x7f0600a7
			public const int _108sdp = 2131099815;
			
			// aapt resource value: 0x7f0600a8
			public const int _109sdp = 2131099816;
			
			// aapt resource value: 0x7f060045
			public const int _10sdp = 2131099717;
			
			// aapt resource value: 0x7f0600a9
			public const int _110sdp = 2131099817;
			
			// aapt resource value: 0x7f0600aa
			public const int _111sdp = 2131099818;
			
			// aapt resource value: 0x7f0600ab
			public const int _112sdp = 2131099819;
			
			// aapt resource value: 0x7f0600ac
			public const int _113sdp = 2131099820;
			
			// aapt resource value: 0x7f0600ad
			public const int _114sdp = 2131099821;
			
			// aapt resource value: 0x7f0600ae
			public const int _115sdp = 2131099822;
			
			// aapt resource value: 0x7f0600af
			public const int _116sdp = 2131099823;
			
			// aapt resource value: 0x7f0600b0
			public const int _117sdp = 2131099824;
			
			// aapt resource value: 0x7f0600b1
			public const int _118sdp = 2131099825;
			
			// aapt resource value: 0x7f0600b2
			public const int _119sdp = 2131099826;
			
			// aapt resource value: 0x7f060046
			public const int _11sdp = 2131099718;
			
			// aapt resource value: 0x7f0600b3
			public const int _120sdp = 2131099827;
			
			// aapt resource value: 0x7f0600b4
			public const int _121sdp = 2131099828;
			
			// aapt resource value: 0x7f0600b5
			public const int _122sdp = 2131099829;
			
			// aapt resource value: 0x7f0600b6
			public const int _123sdp = 2131099830;
			
			// aapt resource value: 0x7f0600b7
			public const int _124sdp = 2131099831;
			
			// aapt resource value: 0x7f0600b8
			public const int _125sdp = 2131099832;
			
			// aapt resource value: 0x7f0600b9
			public const int _126sdp = 2131099833;
			
			// aapt resource value: 0x7f0600ba
			public const int _127sdp = 2131099834;
			
			// aapt resource value: 0x7f0600bb
			public const int _128sdp = 2131099835;
			
			// aapt resource value: 0x7f0600bc
			public const int _129sdp = 2131099836;
			
			// aapt resource value: 0x7f060047
			public const int _12sdp = 2131099719;
			
			// aapt resource value: 0x7f0600bd
			public const int _130sdp = 2131099837;
			
			// aapt resource value: 0x7f0600be
			public const int _131sdp = 2131099838;
			
			// aapt resource value: 0x7f0600bf
			public const int _132sdp = 2131099839;
			
			// aapt resource value: 0x7f0600c0
			public const int _133sdp = 2131099840;
			
			// aapt resource value: 0x7f0600c1
			public const int _134sdp = 2131099841;
			
			// aapt resource value: 0x7f0600c2
			public const int _135sdp = 2131099842;
			
			// aapt resource value: 0x7f0600c3
			public const int _136sdp = 2131099843;
			
			// aapt resource value: 0x7f0600c4
			public const int _137sdp = 2131099844;
			
			// aapt resource value: 0x7f0600c5
			public const int _138sdp = 2131099845;
			
			// aapt resource value: 0x7f0600c6
			public const int _139sdp = 2131099846;
			
			// aapt resource value: 0x7f060048
			public const int _13sdp = 2131099720;
			
			// aapt resource value: 0x7f0600c7
			public const int _140sdp = 2131099847;
			
			// aapt resource value: 0x7f0600c8
			public const int _141sdp = 2131099848;
			
			// aapt resource value: 0x7f0600c9
			public const int _142sdp = 2131099849;
			
			// aapt resource value: 0x7f0600ca
			public const int _143sdp = 2131099850;
			
			// aapt resource value: 0x7f0600cb
			public const int _144sdp = 2131099851;
			
			// aapt resource value: 0x7f0600cc
			public const int _145sdp = 2131099852;
			
			// aapt resource value: 0x7f0600cd
			public const int _146sdp = 2131099853;
			
			// aapt resource value: 0x7f0600ce
			public const int _147sdp = 2131099854;
			
			// aapt resource value: 0x7f0600cf
			public const int _148sdp = 2131099855;
			
			// aapt resource value: 0x7f0600d0
			public const int _149sdp = 2131099856;
			
			// aapt resource value: 0x7f060049
			public const int _14sdp = 2131099721;
			
			// aapt resource value: 0x7f0600d1
			public const int _150sdp = 2131099857;
			
			// aapt resource value: 0x7f0600d2
			public const int _151sdp = 2131099858;
			
			// aapt resource value: 0x7f0600d3
			public const int _152sdp = 2131099859;
			
			// aapt resource value: 0x7f0600d4
			public const int _153sdp = 2131099860;
			
			// aapt resource value: 0x7f0600d5
			public const int _154sdp = 2131099861;
			
			// aapt resource value: 0x7f0600d6
			public const int _155sdp = 2131099862;
			
			// aapt resource value: 0x7f0600d7
			public const int _156sdp = 2131099863;
			
			// aapt resource value: 0x7f0600d8
			public const int _157sdp = 2131099864;
			
			// aapt resource value: 0x7f0600d9
			public const int _158sdp = 2131099865;
			
			// aapt resource value: 0x7f0600da
			public const int _159sdp = 2131099866;
			
			// aapt resource value: 0x7f06004a
			public const int _15sdp = 2131099722;
			
			// aapt resource value: 0x7f0600db
			public const int _160sdp = 2131099867;
			
			// aapt resource value: 0x7f0600dc
			public const int _161sdp = 2131099868;
			
			// aapt resource value: 0x7f0600dd
			public const int _162sdp = 2131099869;
			
			// aapt resource value: 0x7f0600de
			public const int _163sdp = 2131099870;
			
			// aapt resource value: 0x7f0600df
			public const int _164sdp = 2131099871;
			
			// aapt resource value: 0x7f0600e0
			public const int _165sdp = 2131099872;
			
			// aapt resource value: 0x7f0600e1
			public const int _166sdp = 2131099873;
			
			// aapt resource value: 0x7f0600e2
			public const int _167sdp = 2131099874;
			
			// aapt resource value: 0x7f0600e3
			public const int _168sdp = 2131099875;
			
			// aapt resource value: 0x7f0600e4
			public const int _169sdp = 2131099876;
			
			// aapt resource value: 0x7f06004b
			public const int _16sdp = 2131099723;
			
			// aapt resource value: 0x7f0600e5
			public const int _170sdp = 2131099877;
			
			// aapt resource value: 0x7f0600e6
			public const int _171sdp = 2131099878;
			
			// aapt resource value: 0x7f0600e7
			public const int _172sdp = 2131099879;
			
			// aapt resource value: 0x7f0600e8
			public const int _173sdp = 2131099880;
			
			// aapt resource value: 0x7f0600e9
			public const int _174sdp = 2131099881;
			
			// aapt resource value: 0x7f0600ea
			public const int _175sdp = 2131099882;
			
			// aapt resource value: 0x7f0600eb
			public const int _176sdp = 2131099883;
			
			// aapt resource value: 0x7f0600ec
			public const int _177sdp = 2131099884;
			
			// aapt resource value: 0x7f0600ed
			public const int _178sdp = 2131099885;
			
			// aapt resource value: 0x7f0600ee
			public const int _179sdp = 2131099886;
			
			// aapt resource value: 0x7f06004c
			public const int _17sdp = 2131099724;
			
			// aapt resource value: 0x7f0600ef
			public const int _180sdp = 2131099887;
			
			// aapt resource value: 0x7f0600f0
			public const int _181sdp = 2131099888;
			
			// aapt resource value: 0x7f0600f1
			public const int _182sdp = 2131099889;
			
			// aapt resource value: 0x7f0600f2
			public const int _183sdp = 2131099890;
			
			// aapt resource value: 0x7f0600f3
			public const int _184sdp = 2131099891;
			
			// aapt resource value: 0x7f0600f4
			public const int _185sdp = 2131099892;
			
			// aapt resource value: 0x7f0600f5
			public const int _186sdp = 2131099893;
			
			// aapt resource value: 0x7f0600f6
			public const int _187sdp = 2131099894;
			
			// aapt resource value: 0x7f0600f7
			public const int _188sdp = 2131099895;
			
			// aapt resource value: 0x7f0600f8
			public const int _189sdp = 2131099896;
			
			// aapt resource value: 0x7f06004d
			public const int _18sdp = 2131099725;
			
			// aapt resource value: 0x7f0600f9
			public const int _190sdp = 2131099897;
			
			// aapt resource value: 0x7f0600fa
			public const int _191sdp = 2131099898;
			
			// aapt resource value: 0x7f0600fb
			public const int _192sdp = 2131099899;
			
			// aapt resource value: 0x7f0600fc
			public const int _193sdp = 2131099900;
			
			// aapt resource value: 0x7f0600fd
			public const int _194sdp = 2131099901;
			
			// aapt resource value: 0x7f0600fe
			public const int _195sdp = 2131099902;
			
			// aapt resource value: 0x7f0600ff
			public const int _196sdp = 2131099903;
			
			// aapt resource value: 0x7f060100
			public const int _197sdp = 2131099904;
			
			// aapt resource value: 0x7f060101
			public const int _198sdp = 2131099905;
			
			// aapt resource value: 0x7f060102
			public const int _199sdp = 2131099906;
			
			// aapt resource value: 0x7f06004e
			public const int _19sdp = 2131099726;
			
			// aapt resource value: 0x7f06003c
			public const int _1sdp = 2131099708;
			
			// aapt resource value: 0x7f060103
			public const int _200sdp = 2131099907;
			
			// aapt resource value: 0x7f060104
			public const int _201sdp = 2131099908;
			
			// aapt resource value: 0x7f060105
			public const int _202sdp = 2131099909;
			
			// aapt resource value: 0x7f060106
			public const int _203sdp = 2131099910;
			
			// aapt resource value: 0x7f060107
			public const int _204sdp = 2131099911;
			
			// aapt resource value: 0x7f060108
			public const int _205sdp = 2131099912;
			
			// aapt resource value: 0x7f060109
			public const int _206sdp = 2131099913;
			
			// aapt resource value: 0x7f06010a
			public const int _207sdp = 2131099914;
			
			// aapt resource value: 0x7f06010b
			public const int _208sdp = 2131099915;
			
			// aapt resource value: 0x7f06010c
			public const int _209sdp = 2131099916;
			
			// aapt resource value: 0x7f06004f
			public const int _20sdp = 2131099727;
			
			// aapt resource value: 0x7f06010d
			public const int _210sdp = 2131099917;
			
			// aapt resource value: 0x7f06010e
			public const int _211sdp = 2131099918;
			
			// aapt resource value: 0x7f06010f
			public const int _212sdp = 2131099919;
			
			// aapt resource value: 0x7f060110
			public const int _213sdp = 2131099920;
			
			// aapt resource value: 0x7f060111
			public const int _214sdp = 2131099921;
			
			// aapt resource value: 0x7f060112
			public const int _215sdp = 2131099922;
			
			// aapt resource value: 0x7f060113
			public const int _216sdp = 2131099923;
			
			// aapt resource value: 0x7f060114
			public const int _217sdp = 2131099924;
			
			// aapt resource value: 0x7f060115
			public const int _218sdp = 2131099925;
			
			// aapt resource value: 0x7f060116
			public const int _219sdp = 2131099926;
			
			// aapt resource value: 0x7f060050
			public const int _21sdp = 2131099728;
			
			// aapt resource value: 0x7f060117
			public const int _220sdp = 2131099927;
			
			// aapt resource value: 0x7f060118
			public const int _221sdp = 2131099928;
			
			// aapt resource value: 0x7f060119
			public const int _222sdp = 2131099929;
			
			// aapt resource value: 0x7f06011a
			public const int _223sdp = 2131099930;
			
			// aapt resource value: 0x7f06011b
			public const int _224sdp = 2131099931;
			
			// aapt resource value: 0x7f06011c
			public const int _225sdp = 2131099932;
			
			// aapt resource value: 0x7f06011d
			public const int _226sdp = 2131099933;
			
			// aapt resource value: 0x7f06011e
			public const int _227sdp = 2131099934;
			
			// aapt resource value: 0x7f06011f
			public const int _228sdp = 2131099935;
			
			// aapt resource value: 0x7f060120
			public const int _229sdp = 2131099936;
			
			// aapt resource value: 0x7f060051
			public const int _22sdp = 2131099729;
			
			// aapt resource value: 0x7f060121
			public const int _230sdp = 2131099937;
			
			// aapt resource value: 0x7f060122
			public const int _231sdp = 2131099938;
			
			// aapt resource value: 0x7f060123
			public const int _232sdp = 2131099939;
			
			// aapt resource value: 0x7f060124
			public const int _233sdp = 2131099940;
			
			// aapt resource value: 0x7f060125
			public const int _234sdp = 2131099941;
			
			// aapt resource value: 0x7f060126
			public const int _235sdp = 2131099942;
			
			// aapt resource value: 0x7f060127
			public const int _236sdp = 2131099943;
			
			// aapt resource value: 0x7f060128
			public const int _237sdp = 2131099944;
			
			// aapt resource value: 0x7f060129
			public const int _238sdp = 2131099945;
			
			// aapt resource value: 0x7f06012a
			public const int _239sdp = 2131099946;
			
			// aapt resource value: 0x7f060052
			public const int _23sdp = 2131099730;
			
			// aapt resource value: 0x7f06012b
			public const int _240sdp = 2131099947;
			
			// aapt resource value: 0x7f06012c
			public const int _241sdp = 2131099948;
			
			// aapt resource value: 0x7f06012d
			public const int _242sdp = 2131099949;
			
			// aapt resource value: 0x7f06012e
			public const int _243sdp = 2131099950;
			
			// aapt resource value: 0x7f06012f
			public const int _244sdp = 2131099951;
			
			// aapt resource value: 0x7f060130
			public const int _245sdp = 2131099952;
			
			// aapt resource value: 0x7f060131
			public const int _246sdp = 2131099953;
			
			// aapt resource value: 0x7f060132
			public const int _247sdp = 2131099954;
			
			// aapt resource value: 0x7f060133
			public const int _248sdp = 2131099955;
			
			// aapt resource value: 0x7f060134
			public const int _249sdp = 2131099956;
			
			// aapt resource value: 0x7f060053
			public const int _24sdp = 2131099731;
			
			// aapt resource value: 0x7f060135
			public const int _250sdp = 2131099957;
			
			// aapt resource value: 0x7f060136
			public const int _251sdp = 2131099958;
			
			// aapt resource value: 0x7f060137
			public const int _252sdp = 2131099959;
			
			// aapt resource value: 0x7f060138
			public const int _253sdp = 2131099960;
			
			// aapt resource value: 0x7f060139
			public const int _254sdp = 2131099961;
			
			// aapt resource value: 0x7f06013a
			public const int _255sdp = 2131099962;
			
			// aapt resource value: 0x7f06013b
			public const int _256sdp = 2131099963;
			
			// aapt resource value: 0x7f06013c
			public const int _257sdp = 2131099964;
			
			// aapt resource value: 0x7f06013d
			public const int _258sdp = 2131099965;
			
			// aapt resource value: 0x7f06013e
			public const int _259sdp = 2131099966;
			
			// aapt resource value: 0x7f060054
			public const int _25sdp = 2131099732;
			
			// aapt resource value: 0x7f06013f
			public const int _260sdp = 2131099967;
			
			// aapt resource value: 0x7f060140
			public const int _261sdp = 2131099968;
			
			// aapt resource value: 0x7f060141
			public const int _262sdp = 2131099969;
			
			// aapt resource value: 0x7f060142
			public const int _263sdp = 2131099970;
			
			// aapt resource value: 0x7f060143
			public const int _264sdp = 2131099971;
			
			// aapt resource value: 0x7f060144
			public const int _265sdp = 2131099972;
			
			// aapt resource value: 0x7f060145
			public const int _266sdp = 2131099973;
			
			// aapt resource value: 0x7f060146
			public const int _267sdp = 2131099974;
			
			// aapt resource value: 0x7f060147
			public const int _268sdp = 2131099975;
			
			// aapt resource value: 0x7f060148
			public const int _269sdp = 2131099976;
			
			// aapt resource value: 0x7f060055
			public const int _26sdp = 2131099733;
			
			// aapt resource value: 0x7f060149
			public const int _270sdp = 2131099977;
			
			// aapt resource value: 0x7f06014a
			public const int _271sdp = 2131099978;
			
			// aapt resource value: 0x7f06014b
			public const int _272sdp = 2131099979;
			
			// aapt resource value: 0x7f06014c
			public const int _273sdp = 2131099980;
			
			// aapt resource value: 0x7f06014d
			public const int _274sdp = 2131099981;
			
			// aapt resource value: 0x7f06014e
			public const int _275sdp = 2131099982;
			
			// aapt resource value: 0x7f06014f
			public const int _276sdp = 2131099983;
			
			// aapt resource value: 0x7f060150
			public const int _277sdp = 2131099984;
			
			// aapt resource value: 0x7f060151
			public const int _278sdp = 2131099985;
			
			// aapt resource value: 0x7f060152
			public const int _279sdp = 2131099986;
			
			// aapt resource value: 0x7f060056
			public const int _27sdp = 2131099734;
			
			// aapt resource value: 0x7f060153
			public const int _280sdp = 2131099987;
			
			// aapt resource value: 0x7f060154
			public const int _281sdp = 2131099988;
			
			// aapt resource value: 0x7f060155
			public const int _282sdp = 2131099989;
			
			// aapt resource value: 0x7f060156
			public const int _283sdp = 2131099990;
			
			// aapt resource value: 0x7f060157
			public const int _284sdp = 2131099991;
			
			// aapt resource value: 0x7f060158
			public const int _285sdp = 2131099992;
			
			// aapt resource value: 0x7f060159
			public const int _286sdp = 2131099993;
			
			// aapt resource value: 0x7f06015a
			public const int _287sdp = 2131099994;
			
			// aapt resource value: 0x7f06015b
			public const int _288sdp = 2131099995;
			
			// aapt resource value: 0x7f06015c
			public const int _289sdp = 2131099996;
			
			// aapt resource value: 0x7f060057
			public const int _28sdp = 2131099735;
			
			// aapt resource value: 0x7f06015d
			public const int _290sdp = 2131099997;
			
			// aapt resource value: 0x7f06015e
			public const int _291sdp = 2131099998;
			
			// aapt resource value: 0x7f06015f
			public const int _292sdp = 2131099999;
			
			// aapt resource value: 0x7f060160
			public const int _293sdp = 2131100000;
			
			// aapt resource value: 0x7f060161
			public const int _294sdp = 2131100001;
			
			// aapt resource value: 0x7f060162
			public const int _295sdp = 2131100002;
			
			// aapt resource value: 0x7f060163
			public const int _296sdp = 2131100003;
			
			// aapt resource value: 0x7f060164
			public const int _297sdp = 2131100004;
			
			// aapt resource value: 0x7f060165
			public const int _298sdp = 2131100005;
			
			// aapt resource value: 0x7f060166
			public const int _299sdp = 2131100006;
			
			// aapt resource value: 0x7f060058
			public const int _29sdp = 2131099736;
			
			// aapt resource value: 0x7f06003d
			public const int _2sdp = 2131099709;
			
			// aapt resource value: 0x7f060167
			public const int _300sdp = 2131100007;
			
			// aapt resource value: 0x7f060168
			public const int _301sdp = 2131100008;
			
			// aapt resource value: 0x7f060169
			public const int _302sdp = 2131100009;
			
			// aapt resource value: 0x7f06016a
			public const int _303sdp = 2131100010;
			
			// aapt resource value: 0x7f06016b
			public const int _304sdp = 2131100011;
			
			// aapt resource value: 0x7f06016c
			public const int _305sdp = 2131100012;
			
			// aapt resource value: 0x7f06016d
			public const int _306sdp = 2131100013;
			
			// aapt resource value: 0x7f06016e
			public const int _307sdp = 2131100014;
			
			// aapt resource value: 0x7f06016f
			public const int _308sdp = 2131100015;
			
			// aapt resource value: 0x7f060170
			public const int _309sdp = 2131100016;
			
			// aapt resource value: 0x7f060059
			public const int _30sdp = 2131099737;
			
			// aapt resource value: 0x7f060171
			public const int _310sdp = 2131100017;
			
			// aapt resource value: 0x7f060172
			public const int _311sdp = 2131100018;
			
			// aapt resource value: 0x7f060173
			public const int _312sdp = 2131100019;
			
			// aapt resource value: 0x7f060174
			public const int _313sdp = 2131100020;
			
			// aapt resource value: 0x7f060175
			public const int _314sdp = 2131100021;
			
			// aapt resource value: 0x7f060176
			public const int _315sdp = 2131100022;
			
			// aapt resource value: 0x7f060177
			public const int _316sdp = 2131100023;
			
			// aapt resource value: 0x7f060178
			public const int _317sdp = 2131100024;
			
			// aapt resource value: 0x7f060179
			public const int _318sdp = 2131100025;
			
			// aapt resource value: 0x7f06017a
			public const int _319sdp = 2131100026;
			
			// aapt resource value: 0x7f06005a
			public const int _31sdp = 2131099738;
			
			// aapt resource value: 0x7f06017b
			public const int _320sdp = 2131100027;
			
			// aapt resource value: 0x7f06017c
			public const int _321sdp = 2131100028;
			
			// aapt resource value: 0x7f06017d
			public const int _322sdp = 2131100029;
			
			// aapt resource value: 0x7f06017e
			public const int _323sdp = 2131100030;
			
			// aapt resource value: 0x7f06017f
			public const int _324sdp = 2131100031;
			
			// aapt resource value: 0x7f060180
			public const int _325sdp = 2131100032;
			
			// aapt resource value: 0x7f060181
			public const int _326sdp = 2131100033;
			
			// aapt resource value: 0x7f060182
			public const int _327sdp = 2131100034;
			
			// aapt resource value: 0x7f060183
			public const int _328sdp = 2131100035;
			
			// aapt resource value: 0x7f060184
			public const int _329sdp = 2131100036;
			
			// aapt resource value: 0x7f06005b
			public const int _32sdp = 2131099739;
			
			// aapt resource value: 0x7f060185
			public const int _330sdp = 2131100037;
			
			// aapt resource value: 0x7f060186
			public const int _331sdp = 2131100038;
			
			// aapt resource value: 0x7f060187
			public const int _332sdp = 2131100039;
			
			// aapt resource value: 0x7f060188
			public const int _333sdp = 2131100040;
			
			// aapt resource value: 0x7f060189
			public const int _334sdp = 2131100041;
			
			// aapt resource value: 0x7f06018a
			public const int _335sdp = 2131100042;
			
			// aapt resource value: 0x7f06018b
			public const int _336sdp = 2131100043;
			
			// aapt resource value: 0x7f06018c
			public const int _337sdp = 2131100044;
			
			// aapt resource value: 0x7f06018d
			public const int _338sdp = 2131100045;
			
			// aapt resource value: 0x7f06018e
			public const int _339sdp = 2131100046;
			
			// aapt resource value: 0x7f06005c
			public const int _33sdp = 2131099740;
			
			// aapt resource value: 0x7f06018f
			public const int _340sdp = 2131100047;
			
			// aapt resource value: 0x7f060190
			public const int _341sdp = 2131100048;
			
			// aapt resource value: 0x7f060191
			public const int _342sdp = 2131100049;
			
			// aapt resource value: 0x7f060192
			public const int _343sdp = 2131100050;
			
			// aapt resource value: 0x7f060193
			public const int _344sdp = 2131100051;
			
			// aapt resource value: 0x7f060194
			public const int _345sdp = 2131100052;
			
			// aapt resource value: 0x7f060195
			public const int _346sdp = 2131100053;
			
			// aapt resource value: 0x7f060196
			public const int _347sdp = 2131100054;
			
			// aapt resource value: 0x7f060197
			public const int _348sdp = 2131100055;
			
			// aapt resource value: 0x7f060198
			public const int _349sdp = 2131100056;
			
			// aapt resource value: 0x7f06005d
			public const int _34sdp = 2131099741;
			
			// aapt resource value: 0x7f060199
			public const int _350sdp = 2131100057;
			
			// aapt resource value: 0x7f06019a
			public const int _351sdp = 2131100058;
			
			// aapt resource value: 0x7f06019b
			public const int _352sdp = 2131100059;
			
			// aapt resource value: 0x7f06019c
			public const int _353sdp = 2131100060;
			
			// aapt resource value: 0x7f06019d
			public const int _354sdp = 2131100061;
			
			// aapt resource value: 0x7f06019e
			public const int _355sdp = 2131100062;
			
			// aapt resource value: 0x7f06019f
			public const int _356sdp = 2131100063;
			
			// aapt resource value: 0x7f0601a0
			public const int _357sdp = 2131100064;
			
			// aapt resource value: 0x7f0601a1
			public const int _358sdp = 2131100065;
			
			// aapt resource value: 0x7f0601a2
			public const int _359sdp = 2131100066;
			
			// aapt resource value: 0x7f06005e
			public const int _35sdp = 2131099742;
			
			// aapt resource value: 0x7f0601a3
			public const int _360sdp = 2131100067;
			
			// aapt resource value: 0x7f0601a4
			public const int _361sdp = 2131100068;
			
			// aapt resource value: 0x7f0601a5
			public const int _362sdp = 2131100069;
			
			// aapt resource value: 0x7f0601a6
			public const int _363sdp = 2131100070;
			
			// aapt resource value: 0x7f0601a7
			public const int _364sdp = 2131100071;
			
			// aapt resource value: 0x7f0601a8
			public const int _365sdp = 2131100072;
			
			// aapt resource value: 0x7f0601a9
			public const int _366sdp = 2131100073;
			
			// aapt resource value: 0x7f0601aa
			public const int _367sdp = 2131100074;
			
			// aapt resource value: 0x7f0601ab
			public const int _368sdp = 2131100075;
			
			// aapt resource value: 0x7f0601ac
			public const int _369sdp = 2131100076;
			
			// aapt resource value: 0x7f06005f
			public const int _36sdp = 2131099743;
			
			// aapt resource value: 0x7f0601ad
			public const int _370sdp = 2131100077;
			
			// aapt resource value: 0x7f0601ae
			public const int _371sdp = 2131100078;
			
			// aapt resource value: 0x7f0601af
			public const int _372sdp = 2131100079;
			
			// aapt resource value: 0x7f0601b0
			public const int _373sdp = 2131100080;
			
			// aapt resource value: 0x7f0601b1
			public const int _374sdp = 2131100081;
			
			// aapt resource value: 0x7f0601b2
			public const int _375sdp = 2131100082;
			
			// aapt resource value: 0x7f0601b3
			public const int _376sdp = 2131100083;
			
			// aapt resource value: 0x7f0601b4
			public const int _377sdp = 2131100084;
			
			// aapt resource value: 0x7f0601b5
			public const int _378sdp = 2131100085;
			
			// aapt resource value: 0x7f0601b6
			public const int _379sdp = 2131100086;
			
			// aapt resource value: 0x7f060060
			public const int _37sdp = 2131099744;
			
			// aapt resource value: 0x7f0601b7
			public const int _380sdp = 2131100087;
			
			// aapt resource value: 0x7f0601b8
			public const int _381sdp = 2131100088;
			
			// aapt resource value: 0x7f0601b9
			public const int _382sdp = 2131100089;
			
			// aapt resource value: 0x7f0601ba
			public const int _383sdp = 2131100090;
			
			// aapt resource value: 0x7f0601bb
			public const int _384sdp = 2131100091;
			
			// aapt resource value: 0x7f0601bc
			public const int _385sdp = 2131100092;
			
			// aapt resource value: 0x7f0601bd
			public const int _386sdp = 2131100093;
			
			// aapt resource value: 0x7f0601be
			public const int _387sdp = 2131100094;
			
			// aapt resource value: 0x7f0601bf
			public const int _388sdp = 2131100095;
			
			// aapt resource value: 0x7f0601c0
			public const int _389sdp = 2131100096;
			
			// aapt resource value: 0x7f060061
			public const int _38sdp = 2131099745;
			
			// aapt resource value: 0x7f0601c1
			public const int _390sdp = 2131100097;
			
			// aapt resource value: 0x7f0601c2
			public const int _391sdp = 2131100098;
			
			// aapt resource value: 0x7f0601c3
			public const int _392sdp = 2131100099;
			
			// aapt resource value: 0x7f0601c4
			public const int _393sdp = 2131100100;
			
			// aapt resource value: 0x7f0601c5
			public const int _394sdp = 2131100101;
			
			// aapt resource value: 0x7f0601c6
			public const int _395sdp = 2131100102;
			
			// aapt resource value: 0x7f0601c7
			public const int _396sdp = 2131100103;
			
			// aapt resource value: 0x7f0601c8
			public const int _397sdp = 2131100104;
			
			// aapt resource value: 0x7f0601c9
			public const int _398sdp = 2131100105;
			
			// aapt resource value: 0x7f0601ca
			public const int _399sdp = 2131100106;
			
			// aapt resource value: 0x7f060062
			public const int _39sdp = 2131099746;
			
			// aapt resource value: 0x7f06003e
			public const int _3sdp = 2131099710;
			
			// aapt resource value: 0x7f0601cb
			public const int _400sdp = 2131100107;
			
			// aapt resource value: 0x7f0601cc
			public const int _401sdp = 2131100108;
			
			// aapt resource value: 0x7f0601cd
			public const int _402sdp = 2131100109;
			
			// aapt resource value: 0x7f0601ce
			public const int _403sdp = 2131100110;
			
			// aapt resource value: 0x7f0601cf
			public const int _404sdp = 2131100111;
			
			// aapt resource value: 0x7f0601d0
			public const int _405sdp = 2131100112;
			
			// aapt resource value: 0x7f0601d1
			public const int _406sdp = 2131100113;
			
			// aapt resource value: 0x7f0601d2
			public const int _407sdp = 2131100114;
			
			// aapt resource value: 0x7f0601d3
			public const int _408sdp = 2131100115;
			
			// aapt resource value: 0x7f0601d4
			public const int _409sdp = 2131100116;
			
			// aapt resource value: 0x7f060063
			public const int _40sdp = 2131099747;
			
			// aapt resource value: 0x7f0601d5
			public const int _410sdp = 2131100117;
			
			// aapt resource value: 0x7f0601d6
			public const int _411sdp = 2131100118;
			
			// aapt resource value: 0x7f0601d7
			public const int _412sdp = 2131100119;
			
			// aapt resource value: 0x7f0601d8
			public const int _413sdp = 2131100120;
			
			// aapt resource value: 0x7f0601d9
			public const int _414sdp = 2131100121;
			
			// aapt resource value: 0x7f0601da
			public const int _415sdp = 2131100122;
			
			// aapt resource value: 0x7f0601db
			public const int _416sdp = 2131100123;
			
			// aapt resource value: 0x7f0601dc
			public const int _417sdp = 2131100124;
			
			// aapt resource value: 0x7f0601dd
			public const int _418sdp = 2131100125;
			
			// aapt resource value: 0x7f0601de
			public const int _419sdp = 2131100126;
			
			// aapt resource value: 0x7f060064
			public const int _41sdp = 2131099748;
			
			// aapt resource value: 0x7f0601df
			public const int _420sdp = 2131100127;
			
			// aapt resource value: 0x7f0601e0
			public const int _421sdp = 2131100128;
			
			// aapt resource value: 0x7f0601e1
			public const int _422sdp = 2131100129;
			
			// aapt resource value: 0x7f0601e2
			public const int _423sdp = 2131100130;
			
			// aapt resource value: 0x7f0601e3
			public const int _424sdp = 2131100131;
			
			// aapt resource value: 0x7f0601e4
			public const int _425sdp = 2131100132;
			
			// aapt resource value: 0x7f0601e5
			public const int _426sdp = 2131100133;
			
			// aapt resource value: 0x7f0601e6
			public const int _427sdp = 2131100134;
			
			// aapt resource value: 0x7f0601e7
			public const int _428sdp = 2131100135;
			
			// aapt resource value: 0x7f0601e8
			public const int _429sdp = 2131100136;
			
			// aapt resource value: 0x7f060065
			public const int _42sdp = 2131099749;
			
			// aapt resource value: 0x7f0601e9
			public const int _430sdp = 2131100137;
			
			// aapt resource value: 0x7f0601ea
			public const int _431sdp = 2131100138;
			
			// aapt resource value: 0x7f0601eb
			public const int _432sdp = 2131100139;
			
			// aapt resource value: 0x7f0601ec
			public const int _433sdp = 2131100140;
			
			// aapt resource value: 0x7f0601ed
			public const int _434sdp = 2131100141;
			
			// aapt resource value: 0x7f0601ee
			public const int _435sdp = 2131100142;
			
			// aapt resource value: 0x7f0601ef
			public const int _436sdp = 2131100143;
			
			// aapt resource value: 0x7f0601f0
			public const int _437sdp = 2131100144;
			
			// aapt resource value: 0x7f0601f1
			public const int _438sdp = 2131100145;
			
			// aapt resource value: 0x7f0601f2
			public const int _439sdp = 2131100146;
			
			// aapt resource value: 0x7f060066
			public const int _43sdp = 2131099750;
			
			// aapt resource value: 0x7f0601f3
			public const int _440sdp = 2131100147;
			
			// aapt resource value: 0x7f0601f4
			public const int _441sdp = 2131100148;
			
			// aapt resource value: 0x7f0601f5
			public const int _442sdp = 2131100149;
			
			// aapt resource value: 0x7f0601f6
			public const int _443sdp = 2131100150;
			
			// aapt resource value: 0x7f0601f7
			public const int _444sdp = 2131100151;
			
			// aapt resource value: 0x7f0601f8
			public const int _445sdp = 2131100152;
			
			// aapt resource value: 0x7f0601f9
			public const int _446sdp = 2131100153;
			
			// aapt resource value: 0x7f0601fa
			public const int _447sdp = 2131100154;
			
			// aapt resource value: 0x7f0601fb
			public const int _448sdp = 2131100155;
			
			// aapt resource value: 0x7f0601fc
			public const int _449sdp = 2131100156;
			
			// aapt resource value: 0x7f060067
			public const int _44sdp = 2131099751;
			
			// aapt resource value: 0x7f0601fd
			public const int _450sdp = 2131100157;
			
			// aapt resource value: 0x7f0601fe
			public const int _451sdp = 2131100158;
			
			// aapt resource value: 0x7f0601ff
			public const int _452sdp = 2131100159;
			
			// aapt resource value: 0x7f060200
			public const int _453sdp = 2131100160;
			
			// aapt resource value: 0x7f060201
			public const int _454sdp = 2131100161;
			
			// aapt resource value: 0x7f060202
			public const int _455sdp = 2131100162;
			
			// aapt resource value: 0x7f060203
			public const int _456sdp = 2131100163;
			
			// aapt resource value: 0x7f060204
			public const int _457sdp = 2131100164;
			
			// aapt resource value: 0x7f060205
			public const int _458sdp = 2131100165;
			
			// aapt resource value: 0x7f060206
			public const int _459sdp = 2131100166;
			
			// aapt resource value: 0x7f060068
			public const int _45sdp = 2131099752;
			
			// aapt resource value: 0x7f060207
			public const int _460sdp = 2131100167;
			
			// aapt resource value: 0x7f060208
			public const int _461sdp = 2131100168;
			
			// aapt resource value: 0x7f060209
			public const int _462sdp = 2131100169;
			
			// aapt resource value: 0x7f06020a
			public const int _463sdp = 2131100170;
			
			// aapt resource value: 0x7f06020b
			public const int _464sdp = 2131100171;
			
			// aapt resource value: 0x7f06020c
			public const int _465sdp = 2131100172;
			
			// aapt resource value: 0x7f06020d
			public const int _466sdp = 2131100173;
			
			// aapt resource value: 0x7f06020e
			public const int _467sdp = 2131100174;
			
			// aapt resource value: 0x7f06020f
			public const int _468sdp = 2131100175;
			
			// aapt resource value: 0x7f060210
			public const int _469sdp = 2131100176;
			
			// aapt resource value: 0x7f060069
			public const int _46sdp = 2131099753;
			
			// aapt resource value: 0x7f060211
			public const int _470sdp = 2131100177;
			
			// aapt resource value: 0x7f060212
			public const int _471sdp = 2131100178;
			
			// aapt resource value: 0x7f060213
			public const int _472sdp = 2131100179;
			
			// aapt resource value: 0x7f060214
			public const int _473sdp = 2131100180;
			
			// aapt resource value: 0x7f060215
			public const int _474sdp = 2131100181;
			
			// aapt resource value: 0x7f060216
			public const int _475sdp = 2131100182;
			
			// aapt resource value: 0x7f060217
			public const int _476sdp = 2131100183;
			
			// aapt resource value: 0x7f060218
			public const int _477sdp = 2131100184;
			
			// aapt resource value: 0x7f060219
			public const int _478sdp = 2131100185;
			
			// aapt resource value: 0x7f06021a
			public const int _479sdp = 2131100186;
			
			// aapt resource value: 0x7f06006a
			public const int _47sdp = 2131099754;
			
			// aapt resource value: 0x7f06021b
			public const int _480sdp = 2131100187;
			
			// aapt resource value: 0x7f06021c
			public const int _481sdp = 2131100188;
			
			// aapt resource value: 0x7f06021d
			public const int _482sdp = 2131100189;
			
			// aapt resource value: 0x7f06021e
			public const int _483sdp = 2131100190;
			
			// aapt resource value: 0x7f06021f
			public const int _484sdp = 2131100191;
			
			// aapt resource value: 0x7f060220
			public const int _485sdp = 2131100192;
			
			// aapt resource value: 0x7f060221
			public const int _486sdp = 2131100193;
			
			// aapt resource value: 0x7f060222
			public const int _487sdp = 2131100194;
			
			// aapt resource value: 0x7f060223
			public const int _488sdp = 2131100195;
			
			// aapt resource value: 0x7f060224
			public const int _489sdp = 2131100196;
			
			// aapt resource value: 0x7f06006b
			public const int _48sdp = 2131099755;
			
			// aapt resource value: 0x7f060225
			public const int _490sdp = 2131100197;
			
			// aapt resource value: 0x7f060226
			public const int _491sdp = 2131100198;
			
			// aapt resource value: 0x7f060227
			public const int _492sdp = 2131100199;
			
			// aapt resource value: 0x7f060228
			public const int _493sdp = 2131100200;
			
			// aapt resource value: 0x7f060229
			public const int _494sdp = 2131100201;
			
			// aapt resource value: 0x7f06022a
			public const int _495sdp = 2131100202;
			
			// aapt resource value: 0x7f06022b
			public const int _496sdp = 2131100203;
			
			// aapt resource value: 0x7f06022c
			public const int _497sdp = 2131100204;
			
			// aapt resource value: 0x7f06022d
			public const int _498sdp = 2131100205;
			
			// aapt resource value: 0x7f06022e
			public const int _499sdp = 2131100206;
			
			// aapt resource value: 0x7f06006c
			public const int _49sdp = 2131099756;
			
			// aapt resource value: 0x7f06003f
			public const int _4sdp = 2131099711;
			
			// aapt resource value: 0x7f06022f
			public const int _500sdp = 2131100207;
			
			// aapt resource value: 0x7f060230
			public const int _501sdp = 2131100208;
			
			// aapt resource value: 0x7f060231
			public const int _502sdp = 2131100209;
			
			// aapt resource value: 0x7f060232
			public const int _503sdp = 2131100210;
			
			// aapt resource value: 0x7f060233
			public const int _504sdp = 2131100211;
			
			// aapt resource value: 0x7f060234
			public const int _505sdp = 2131100212;
			
			// aapt resource value: 0x7f060235
			public const int _506sdp = 2131100213;
			
			// aapt resource value: 0x7f060236
			public const int _507sdp = 2131100214;
			
			// aapt resource value: 0x7f060237
			public const int _508sdp = 2131100215;
			
			// aapt resource value: 0x7f060238
			public const int _509sdp = 2131100216;
			
			// aapt resource value: 0x7f06006d
			public const int _50sdp = 2131099757;
			
			// aapt resource value: 0x7f060239
			public const int _510sdp = 2131100217;
			
			// aapt resource value: 0x7f06023a
			public const int _511sdp = 2131100218;
			
			// aapt resource value: 0x7f06023b
			public const int _512sdp = 2131100219;
			
			// aapt resource value: 0x7f06023c
			public const int _513sdp = 2131100220;
			
			// aapt resource value: 0x7f06023d
			public const int _514sdp = 2131100221;
			
			// aapt resource value: 0x7f06023e
			public const int _515sdp = 2131100222;
			
			// aapt resource value: 0x7f06023f
			public const int _516sdp = 2131100223;
			
			// aapt resource value: 0x7f060240
			public const int _517sdp = 2131100224;
			
			// aapt resource value: 0x7f060241
			public const int _518sdp = 2131100225;
			
			// aapt resource value: 0x7f060242
			public const int _519sdp = 2131100226;
			
			// aapt resource value: 0x7f06006e
			public const int _51sdp = 2131099758;
			
			// aapt resource value: 0x7f060243
			public const int _520sdp = 2131100227;
			
			// aapt resource value: 0x7f060244
			public const int _521sdp = 2131100228;
			
			// aapt resource value: 0x7f060245
			public const int _522sdp = 2131100229;
			
			// aapt resource value: 0x7f060246
			public const int _523sdp = 2131100230;
			
			// aapt resource value: 0x7f060247
			public const int _524sdp = 2131100231;
			
			// aapt resource value: 0x7f060248
			public const int _525sdp = 2131100232;
			
			// aapt resource value: 0x7f060249
			public const int _526sdp = 2131100233;
			
			// aapt resource value: 0x7f06024a
			public const int _527sdp = 2131100234;
			
			// aapt resource value: 0x7f06024b
			public const int _528sdp = 2131100235;
			
			// aapt resource value: 0x7f06024c
			public const int _529sdp = 2131100236;
			
			// aapt resource value: 0x7f06006f
			public const int _52sdp = 2131099759;
			
			// aapt resource value: 0x7f06024d
			public const int _530sdp = 2131100237;
			
			// aapt resource value: 0x7f06024e
			public const int _531sdp = 2131100238;
			
			// aapt resource value: 0x7f06024f
			public const int _532sdp = 2131100239;
			
			// aapt resource value: 0x7f060250
			public const int _533sdp = 2131100240;
			
			// aapt resource value: 0x7f060251
			public const int _534sdp = 2131100241;
			
			// aapt resource value: 0x7f060252
			public const int _535sdp = 2131100242;
			
			// aapt resource value: 0x7f060253
			public const int _536sdp = 2131100243;
			
			// aapt resource value: 0x7f060254
			public const int _537sdp = 2131100244;
			
			// aapt resource value: 0x7f060255
			public const int _538sdp = 2131100245;
			
			// aapt resource value: 0x7f060256
			public const int _539sdp = 2131100246;
			
			// aapt resource value: 0x7f060070
			public const int _53sdp = 2131099760;
			
			// aapt resource value: 0x7f060257
			public const int _540sdp = 2131100247;
			
			// aapt resource value: 0x7f060258
			public const int _541sdp = 2131100248;
			
			// aapt resource value: 0x7f060259
			public const int _542sdp = 2131100249;
			
			// aapt resource value: 0x7f06025a
			public const int _543sdp = 2131100250;
			
			// aapt resource value: 0x7f06025b
			public const int _544sdp = 2131100251;
			
			// aapt resource value: 0x7f06025c
			public const int _545sdp = 2131100252;
			
			// aapt resource value: 0x7f06025d
			public const int _546sdp = 2131100253;
			
			// aapt resource value: 0x7f06025e
			public const int _547sdp = 2131100254;
			
			// aapt resource value: 0x7f06025f
			public const int _548sdp = 2131100255;
			
			// aapt resource value: 0x7f060260
			public const int _549sdp = 2131100256;
			
			// aapt resource value: 0x7f060071
			public const int _54sdp = 2131099761;
			
			// aapt resource value: 0x7f060261
			public const int _550sdp = 2131100257;
			
			// aapt resource value: 0x7f060262
			public const int _551sdp = 2131100258;
			
			// aapt resource value: 0x7f060263
			public const int _552sdp = 2131100259;
			
			// aapt resource value: 0x7f060264
			public const int _553sdp = 2131100260;
			
			// aapt resource value: 0x7f060265
			public const int _554sdp = 2131100261;
			
			// aapt resource value: 0x7f060266
			public const int _555sdp = 2131100262;
			
			// aapt resource value: 0x7f060267
			public const int _556sdp = 2131100263;
			
			// aapt resource value: 0x7f060268
			public const int _557sdp = 2131100264;
			
			// aapt resource value: 0x7f060269
			public const int _558sdp = 2131100265;
			
			// aapt resource value: 0x7f06026a
			public const int _559sdp = 2131100266;
			
			// aapt resource value: 0x7f060072
			public const int _55sdp = 2131099762;
			
			// aapt resource value: 0x7f06026b
			public const int _560sdp = 2131100267;
			
			// aapt resource value: 0x7f06026c
			public const int _561sdp = 2131100268;
			
			// aapt resource value: 0x7f06026d
			public const int _562sdp = 2131100269;
			
			// aapt resource value: 0x7f06026e
			public const int _563sdp = 2131100270;
			
			// aapt resource value: 0x7f06026f
			public const int _564sdp = 2131100271;
			
			// aapt resource value: 0x7f060270
			public const int _565sdp = 2131100272;
			
			// aapt resource value: 0x7f060271
			public const int _566sdp = 2131100273;
			
			// aapt resource value: 0x7f060272
			public const int _567sdp = 2131100274;
			
			// aapt resource value: 0x7f060273
			public const int _568sdp = 2131100275;
			
			// aapt resource value: 0x7f060274
			public const int _569sdp = 2131100276;
			
			// aapt resource value: 0x7f060073
			public const int _56sdp = 2131099763;
			
			// aapt resource value: 0x7f060275
			public const int _570sdp = 2131100277;
			
			// aapt resource value: 0x7f060276
			public const int _571sdp = 2131100278;
			
			// aapt resource value: 0x7f060277
			public const int _572sdp = 2131100279;
			
			// aapt resource value: 0x7f060278
			public const int _573sdp = 2131100280;
			
			// aapt resource value: 0x7f060279
			public const int _574sdp = 2131100281;
			
			// aapt resource value: 0x7f06027a
			public const int _575sdp = 2131100282;
			
			// aapt resource value: 0x7f06027b
			public const int _576sdp = 2131100283;
			
			// aapt resource value: 0x7f06027c
			public const int _577sdp = 2131100284;
			
			// aapt resource value: 0x7f06027d
			public const int _578sdp = 2131100285;
			
			// aapt resource value: 0x7f06027e
			public const int _579sdp = 2131100286;
			
			// aapt resource value: 0x7f060074
			public const int _57sdp = 2131099764;
			
			// aapt resource value: 0x7f06027f
			public const int _580sdp = 2131100287;
			
			// aapt resource value: 0x7f060280
			public const int _581sdp = 2131100288;
			
			// aapt resource value: 0x7f060281
			public const int _582sdp = 2131100289;
			
			// aapt resource value: 0x7f060282
			public const int _583sdp = 2131100290;
			
			// aapt resource value: 0x7f060283
			public const int _584sdp = 2131100291;
			
			// aapt resource value: 0x7f060284
			public const int _585sdp = 2131100292;
			
			// aapt resource value: 0x7f060285
			public const int _586sdp = 2131100293;
			
			// aapt resource value: 0x7f060286
			public const int _587sdp = 2131100294;
			
			// aapt resource value: 0x7f060287
			public const int _588sdp = 2131100295;
			
			// aapt resource value: 0x7f060288
			public const int _589sdp = 2131100296;
			
			// aapt resource value: 0x7f060075
			public const int _58sdp = 2131099765;
			
			// aapt resource value: 0x7f060289
			public const int _590sdp = 2131100297;
			
			// aapt resource value: 0x7f06028a
			public const int _591sdp = 2131100298;
			
			// aapt resource value: 0x7f06028b
			public const int _592sdp = 2131100299;
			
			// aapt resource value: 0x7f06028c
			public const int _593sdp = 2131100300;
			
			// aapt resource value: 0x7f06028d
			public const int _594sdp = 2131100301;
			
			// aapt resource value: 0x7f06028e
			public const int _595sdp = 2131100302;
			
			// aapt resource value: 0x7f06028f
			public const int _596sdp = 2131100303;
			
			// aapt resource value: 0x7f060290
			public const int _597sdp = 2131100304;
			
			// aapt resource value: 0x7f060291
			public const int _598sdp = 2131100305;
			
			// aapt resource value: 0x7f060292
			public const int _599sdp = 2131100306;
			
			// aapt resource value: 0x7f060076
			public const int _59sdp = 2131099766;
			
			// aapt resource value: 0x7f060040
			public const int _5sdp = 2131099712;
			
			// aapt resource value: 0x7f060293
			public const int _600sdp = 2131100307;
			
			// aapt resource value: 0x7f060077
			public const int _60sdp = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int _61sdp = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int _62sdp = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int _63sdp = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int _64sdp = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int _65sdp = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int _66sdp = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int _67sdp = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int _68sdp = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int _69sdp = 2131099776;
			
			// aapt resource value: 0x7f060041
			public const int _6sdp = 2131099713;
			
			// aapt resource value: 0x7f060081
			public const int _70sdp = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int _71sdp = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int _72sdp = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int _73sdp = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int _74sdp = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int _75sdp = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int _76sdp = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int _77sdp = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int _78sdp = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int _79sdp = 2131099786;
			
			// aapt resource value: 0x7f060042
			public const int _7sdp = 2131099714;
			
			// aapt resource value: 0x7f06008b
			public const int _80sdp = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int _81sdp = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int _82sdp = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int _83sdp = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int _84sdp = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int _85sdp = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int _86sdp = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int _87sdp = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int _88sdp = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int _89sdp = 2131099796;
			
			// aapt resource value: 0x7f060043
			public const int _8sdp = 2131099715;
			
			// aapt resource value: 0x7f060095
			public const int _90sdp = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int _91sdp = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int _92sdp = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int _93sdp = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int _94sdp = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int _95sdp = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int _96sdp = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int _97sdp = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int _98sdp = 2131099805;
			
			// aapt resource value: 0x7f06009e
			public const int _99sdp = 2131099806;
			
			// aapt resource value: 0x7f060044
			public const int _9sdp = 2131099716;
			
			// aapt resource value: 0x7f060009
			public const int _minus10sdp = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int _minus11sdp = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int _minus12sdp = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int _minus13sdp = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int _minus14sdp = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int _minus15sdp = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int _minus16sdp = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int _minus17sdp = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int _minus18sdp = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int _minus19sdp = 2131099666;
			
			// aapt resource value: 0x7f060000
			public const int _minus1sdp = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int _minus20sdp = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int _minus21sdp = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int _minus22sdp = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int _minus23sdp = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int _minus24sdp = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int _minus25sdp = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int _minus26sdp = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int _minus27sdp = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int _minus28sdp = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int _minus29sdp = 2131099676;
			
			// aapt resource value: 0x7f060001
			public const int _minus2sdp = 2131099649;
			
			// aapt resource value: 0x7f06001d
			public const int _minus30sdp = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int _minus31sdp = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int _minus32sdp = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int _minus33sdp = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int _minus34sdp = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int _minus35sdp = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int _minus36sdp = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int _minus37sdp = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int _minus38sdp = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int _minus39sdp = 2131099686;
			
			// aapt resource value: 0x7f060002
			public const int _minus3sdp = 2131099650;
			
			// aapt resource value: 0x7f060027
			public const int _minus40sdp = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int _minus41sdp = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int _minus42sdp = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int _minus43sdp = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int _minus44sdp = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int _minus45sdp = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int _minus46sdp = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int _minus47sdp = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int _minus48sdp = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int _minus49sdp = 2131099696;
			
			// aapt resource value: 0x7f060003
			public const int _minus4sdp = 2131099651;
			
			// aapt resource value: 0x7f060031
			public const int _minus50sdp = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int _minus51sdp = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int _minus52sdp = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int _minus53sdp = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int _minus54sdp = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int _minus55sdp = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int _minus56sdp = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int _minus57sdp = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int _minus58sdp = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int _minus59sdp = 2131099706;
			
			// aapt resource value: 0x7f060004
			public const int _minus5sdp = 2131099652;
			
			// aapt resource value: 0x7f06003b
			public const int _minus60sdp = 2131099707;
			
			// aapt resource value: 0x7f060005
			public const int _minus6sdp = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int _minus7sdp = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int _minus8sdp = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int _minus9sdp = 2131099656;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AlertDialogStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AmountTextBoxBorder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int boxLight = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_small = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ButtonBorder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ButtonStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int checkbox = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int checkbox_tick = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int checkboxstyle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int @checked = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int EditTextBoxBorder = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int FeedbackListItem = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int location = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int menu = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int minus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int passwordicon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int plus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Progress = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int search = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int @unchecked = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int userlisticon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int UserListItemBorder = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int usernameicon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int venue = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090056
			public const int Picker_Date = 2131296342;
			
			// aapt resource value: 0x7f090058
			public const int ScrollView01 = 2131296344;
			
			// aapt resource value: 0x7f09001b
			public const int ScrollViewBody = 2131296283;
			
			// aapt resource value: 0x7f0900bd
			public const int bodyLayout = 2131296445;
			
			// aapt resource value: 0x7f090037
			public const int btnAddPlayer = 2131296311;
			
			// aapt resource value: 0x7f09002f
			public const int btnBatchCountCancel = 2131296303;
			
			// aapt resource value: 0x7f09002e
			public const int btnBatchCountSubmit = 2131296302;
			
			// aapt resource value: 0x7f09003a
			public const int btnCancel = 2131296314;
			
			// aapt resource value: 0x7f09001e
			public const int btnDone = 2131296286;
			
			// aapt resource value: 0x7f0900c2
			public const int btnLogin = 2131296450;
			
			// aapt resource value: 0x7f09006c
			public const int btnNewEnquiry = 2131296364;
			
			// aapt resource value: 0x7f090008
			public const int btnPaste = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public const int btnSubmit = 2131296269;
			
			// aapt resource value: 0x7f0900ad
			public const int btnView = 2131296429;
			
			// aapt resource value: 0x7f090057
			public const int buttonDone = 2131296343;
			
			// aapt resource value: 0x7f0900c1
			public const int buttonLayout = 2131296449;
			
			// aapt resource value: 0x7f09000b
			public const int editTextBookingMessage = 2131296267;
			
			// aapt resource value: 0x7f090064
			public const int editTextEnquiryComment = 2131296356;
			
			// aapt resource value: 0x7f090062
			public const int editTextEnquiryGames = 2131296354;
			
			// aapt resource value: 0x7f09005f
			public const int editTextEnquiryMobile = 2131296351;
			
			// aapt resource value: 0x7f09005d
			public const int editTextEnquiryName = 2131296349;
			
			// aapt resource value: 0x7f090098
			public const int editTextInvoiceDiscountName = 2131296408;
			
			// aapt resource value: 0x7f090099
			public const int editTextInvoiceOthersAmount = 2131296409;
			
			// aapt resource value: 0x7f09009f
			public const int editTextInvoicePayingAmount = 2131296415;
			
			// aapt resource value: 0x7f0900a3
			public const int editTextInvoiceRemarks = 2131296419;
			
			// aapt resource value: 0x7f090093
			public const int editTextInvoiceTotalAmount = 2131296403;
			
			// aapt resource value: 0x7f09009e
			public const int editTextInvoiceTotalPayingAmount = 2131296414;
			
			// aapt resource value: 0x7f09006b
			public const int editTextSearchEnquiryUser = 2131296363;
			
			// aapt resource value: 0x7f0900a7
			public const int editTextSearchInvoiceUser = 2131296423;
			
			// aapt resource value: 0x7f09001a
			public const int editTextSearchPlayer = 2131296282;
			
			// aapt resource value: 0x7f090025
			public const int gridBatch = 2131296293;
			
			// aapt resource value: 0x7f090054
			public const int imgActionBarLocation = 2131296340;
			
			// aapt resource value: 0x7f090085
			public const int imgGameUnchecked = 2131296389;
			
			// aapt resource value: 0x7f090086
			public const int imgGamechecked = 2131296390;
			
			// aapt resource value: 0x7f09003e
			public const int imgIcon = 2131296318;
			
			// aapt resource value: 0x7f09002a
			public const int imgMinus = 2131296298;
			
			// aapt resource value: 0x7f090043
			public const int imgPlayerUnchecked = 2131296323;
			
			// aapt resource value: 0x7f090044
			public const int imgPlayerchecked = 2131296324;
			
			// aapt resource value: 0x7f09002c
			public const int imgPlus = 2131296300;
			
			// aapt resource value: 0x7f090018
			public const int imgSearch = 2131296280;
			
			// aapt resource value: 0x7f0900e5
			public const int lblAppname = 2131296485;
			
			// aapt resource value: 0x7f090023
			public const int lblBatchCount = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int lblBatchName = 2131296290;
			
			// aapt resource value: 0x7f090049
			public const int lblCourtName = 2131296329;
			
			// aapt resource value: 0x7f09007d
			public const int lblEnquiryFeedbackDate = 2131296381;
			
			// aapt resource value: 0x7f09007e
			public const int lblEnquiryUserFeedbackComment = 2131296382;
			
			// aapt resource value: 0x7f090074
			public const int lblEnquiryUserMobile = 2131296372;
			
			// aapt resource value: 0x7f090073
			public const int lblEnquiryUserName = 2131296371;
			
			// aapt resource value: 0x7f090084
			public const int lblGameName = 2131296388;
			
			// aapt resource value: 0x7f0900be
			public const int lblLoginMessage = 2131296446;
			
			// aapt resource value: 0x7f090041
			public const int lblPhone = 2131296321;
			
			// aapt resource value: 0x7f090040
			public const int lblPlayerName = 2131296320;
			
			// aapt resource value: 0x7f0900c5
			public const int lblRememberMe = 2131296453;
			
			// aapt resource value: 0x7f090026
			public const int lblSlot = 2131296294;
			
			// aapt resource value: 0x7f0900db
			public const int lblSportName = 2131296475;
			
			// aapt resource value: 0x7f0900e3
			public const int lblVenueName = 2131296483;
			
			// aapt resource value: 0x7f090006
			public const int lblheader = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int left_fragment_container = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int left_fragment_drawer = 2131296258;
			
			// aapt resource value: 0x7f090055
			public const int linearLayout1 = 2131296341;
			
			// aapt resource value: 0x7f09000e
			public const int linearProgressBar = 2131296270;
			
			// aapt resource value: 0x7f09004e
			public const int llActionBarNameContainer = 2131296334;
			
			// aapt resource value: 0x7f090051
			public const int llActionBarVenueCodeContainer = 2131296337;
			
			// aapt resource value: 0x7f090053
			public const int llActionBarVenueImgContainer = 2131296339;
			
			// aapt resource value: 0x7f090014
			public const int llAlertDialogButton = 2131296276;
			
			// aapt resource value: 0x7f090010
			public const int llAlertDialogContainer = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int llAlertDialogMainContainer = 2131296273;
			
			// aapt resource value: 0x7f090034
			public const int llAttendance = 2131296308;
			
			// aapt resource value: 0x7f09001c
			public const int llAttendanceAddList = 2131296284;
			
			// aapt resource value: 0x7f09003f
			public const int llBatchPlayer = 2131296319;
			
			// aapt resource value: 0x7f090038
			public const int llBatchPlayerList = 2131296312;
			
			// aapt resource value: 0x7f090032
			public const int llBatchesList = 2131296306;
			
			// aapt resource value: 0x7f090065
			public const int llCommentContainer = 2131296357;
			
			// aapt resource value: 0x7f090048
			public const int llCourt = 2131296328;
			
			// aapt resource value: 0x7f09004c
			public const int llCourtList = 2131296332;
			
			// aapt resource value: 0x7f090097
			public const int llDiscountOtherEditText = 2131296407;
			
			// aapt resource value: 0x7f090094
			public const int llDiscountOtherText = 2131296404;
			
			// aapt resource value: 0x7f090067
			public const int llEnquiryFeedbackContainer = 2131296359;
			
			// aapt resource value: 0x7f090076
			public const int llEnquiryFollowUpList = 2131296374;
			
			// aapt resource value: 0x7f090088
			public const int llEnquiryGameList = 2131296392;
			
			// aapt resource value: 0x7f090072
			public const int llEnquiryUser = 2131296370;
			
			// aapt resource value: 0x7f090077
			public const int llEnquiryUserDetails = 2131296375;
			
			// aapt resource value: 0x7f09007c
			public const int llEnquiryUserFeedback = 2131296380;
			
			// aapt resource value: 0x7f09006d
			public const int llEnquiryUserList = 2131296365;
			
			// aapt resource value: 0x7f090059
			public const int llEnquiryViewContainer = 2131296345;
			
			// aapt resource value: 0x7f090083
			public const int llGame = 2131296387;
			
			// aapt resource value: 0x7f09008b
			public const int llInvoiceCollectionFirstViewContainer = 2131296395;
			
			// aapt resource value: 0x7f09008e
			public const int llInvoiceCollectionSecondViewContainer = 2131296398;
			
			// aapt resource value: 0x7f0900ab
			public const int llInvoiceUserContainer = 2131296427;
			
			// aapt resource value: 0x7f0900af
			public const int llInvoiceUserFirstContainer = 2131296431;
			
			// aapt resource value: 0x7f0900b9
			public const int llInvoiceUserHistoryList = 2131296441;
			
			// aapt resource value: 0x7f0900a8
			public const int llInvoiceUserList = 2131296424;
			
			// aapt resource value: 0x7f0900b6
			public const int llInvoiceUserSecondContainer = 2131296438;
			
			// aapt resource value: 0x7f0900b3
			public const int llInvoiceUserSecondContainer1 = 2131296435;
			
			// aapt resource value: 0x7f0900b5
			public const int llInvoiceUserThirdContainer = 2131296437;
			
			// aapt resource value: 0x7f0900c6
			public const int llMenuDrawerMainContainer = 2131296454;
			
			// aapt resource value: 0x7f090007
			public const int llPasteContainer = 2131296263;
			
			// aapt resource value: 0x7f090069
			public const int llSearchEnquiryUser = 2131296361;
			
			// aapt resource value: 0x7f0900a5
			public const int llSearchInvoiceUser = 2131296421;
			
			// aapt resource value: 0x7f090017
			public const int llSearchPlayers = 2131296279;
			
			// aapt resource value: 0x7f090024
			public const int llSlot = 2131296292;
			
			// aapt resource value: 0x7f0900da
			public const int llSport = 2131296474;
			
			// aapt resource value: 0x7f0900dd
			public const int llSportList = 2131296477;
			
			// aapt resource value: 0x7f09009d
			public const int llTotalPaidEditText = 2131296413;
			
			// aapt resource value: 0x7f09009a
			public const int llTotalPaidText = 2131296410;
			
			// aapt resource value: 0x7f0900e2
			public const int llVenue = 2131296482;
			
			// aapt resource value: 0x7f0900e6
			public const int llVenueList = 2131296486;
			
			// aapt resource value: 0x7f09001d
			public const int lstAttendanceAddPlayer = 2131296285;
			
			// aapt resource value: 0x7f090039
			public const int lstBatchPlayer = 2131296313;
			
			// aapt resource value: 0x7f09004d
			public const int lstCourt = 2131296333;
			
			// aapt resource value: 0x7f09006e
			public const int lstEnquiryUser = 2131296366;
			
			// aapt resource value: 0x7f090078
			public const int lstEnquiryUserFollowUpList = 2131296376;
			
			// aapt resource value: 0x7f090089
			public const int lstGames = 2131296393;
			
			// aapt resource value: 0x7f0900a9
			public const int lstInvoiceUser = 2131296425;
			
			// aapt resource value: 0x7f0900ba
			public const int lstInvoiceUserHistory = 2131296442;
			
			// aapt resource value: 0x7f0900de
			public const int lstSport = 2131296478;
			
			// aapt resource value: 0x7f0900e7
			public const int lstVenue = 2131296487;
			
			// aapt resource value: 0x7f090000
			public const int myMenuDrawer = 2131296256;
			
			// aapt resource value: 0x7f0900eb
			public const int nav_FeedBack = 2131296491;
			
			// aapt resource value: 0x7f0900ea
			public const int nav_about = 2131296490;
			
			// aapt resource value: 0x7f0900e8
			public const int nav_home = 2131296488;
			
			// aapt resource value: 0x7f0900e9
			public const int nav_messages = 2131296489;
			
			// aapt resource value: 0x7f0900bb
			public const int parentContainer = 2131296443;
			
			// aapt resource value: 0x7f09000f
			public const int progressring = 2131296271;
			
			// aapt resource value: 0x7f090050
			public const int rlActionBarLocationContainer = 2131296336;
			
			// aapt resource value: 0x7f09004a
			public const int rlAddUserMainContainer = 2131296330;
			
			// aapt resource value: 0x7f090005
			public const int rlAppname = 2131296261;
			
			// aapt resource value: 0x7f090016
			public const int rlAttendanceAddMainContainer = 2131296278;
			
			// aapt resource value: 0x7f090020
			public const int rlBatchContainer = 2131296288;
			
			// aapt resource value: 0x7f090029
			public const int rlBatchCountContainer = 2131296297;
			
			// aapt resource value: 0x7f090027
			public const int rlBatchCountHeader = 2131296295;
			
			// aapt resource value: 0x7f09001f
			public const int rlBatchItemMainContainer = 2131296287;
			
			// aapt resource value: 0x7f09003c
			public const int rlBatchPlayerContainer = 2131296316;
			
			// aapt resource value: 0x7f09003b
			public const int rlBatchPlayerItemMainContainer = 2131296315;
			
			// aapt resource value: 0x7f09003d
			public const int rlBatchPlayerLeftImage = 2131296317;
			
			// aapt resource value: 0x7f090033
			public const int rlBatchPlayerMainContainer = 2131296307;
			
			// aapt resource value: 0x7f090042
			public const int rlBatchPlayerRightImage = 2131296322;
			
			// aapt resource value: 0x7f09002d
			public const int rlBatchSubmitButtonContainer = 2131296301;
			
			// aapt resource value: 0x7f090031
			public const int rlBatchesContainer = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int rlBatchesMainContainer = 2131296304;
			
			// aapt resource value: 0x7f090009
			public const int rlBodyContainer = 2131296265;
			
			// aapt resource value: 0x7f090003
			public const int rlBookingMainContainer = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int rlBottomButtonContainer = 2131296268;
			
			// aapt resource value: 0x7f090046
			public const int rlCourtContainer = 2131296326;
			
			// aapt resource value: 0x7f090045
			public const int rlCourtItemMainContainer = 2131296325;
			
			// aapt resource value: 0x7f090047
			public const int rlCourtLeftImage = 2131296327;
			
			// aapt resource value: 0x7f090070
			public const int rlEnquiryUserContainer = 2131296368;
			
			// aapt resource value: 0x7f090075
			public const int rlEnquiryUserDetailMainContainer = 2131296373;
			
			// aapt resource value: 0x7f09007b
			public const int rlEnquiryUserFeedbackContainer = 2131296379;
			
			// aapt resource value: 0x7f09007a
			public const int rlEnquiryUserFeedbackItemMainContainer = 2131296378;
			
			// aapt resource value: 0x7f09006f
			public const int rlEnquiryUserItemMainContainer = 2131296367;
			
			// aapt resource value: 0x7f090071
			public const int rlEnquiryUserLeftImage = 2131296369;
			
			// aapt resource value: 0x7f090068
			public const int rlEnquiryUserMainContainer = 2131296360;
			
			// aapt resource value: 0x7f090080
			public const int rlGameContainer = 2131296384;
			
			// aapt resource value: 0x7f09007f
			public const int rlGameItemMainContainer = 2131296383;
			
			// aapt resource value: 0x7f090087
			public const int rlGameMainContainer = 2131296391;
			
			// aapt resource value: 0x7f090082
			public const int rlGameRightImage = 2131296386;
			
			// aapt resource value: 0x7f090004
			public const int rlHeader = 2131296260;
			
			// aapt resource value: 0x7f09008a
			public const int rlInvoiceCollectionMainContainer = 2131296394;
			
			// aapt resource value: 0x7f0900b8
			public const int rlInvoiceUserHistoryMainContainer = 2131296440;
			
			// aapt resource value: 0x7f0900aa
			public const int rlInvoiceUserItemMainContainer = 2131296426;
			
			// aapt resource value: 0x7f0900ae
			public const int rlInvoiceUserLeftImage = 2131296430;
			
			// aapt resource value: 0x7f0900a4
			public const int rlInvoiceUserMainContainer = 2131296420;
			
			// aapt resource value: 0x7f0900c3
			public const int rlRememberMe = 2131296451;
			
			// aapt resource value: 0x7f0900ac
			public const int rlRightContainer = 2131296428;
			
			// aapt resource value: 0x7f09004b
			public const int rlSearchView = 2131296331;
			
			// aapt resource value: 0x7f0900d8
			public const int rlSportContainer = 2131296472;
			
			// aapt resource value: 0x7f0900d7
			public const int rlSportItemMainContainer = 2131296471;
			
			// aapt resource value: 0x7f0900d9
			public const int rlSportLeftImage = 2131296473;
			
			// aapt resource value: 0x7f0900dc
			public const int rlSportMainContainer = 2131296476;
			
			// aapt resource value: 0x7f0900e0
			public const int rlVenueContainer = 2131296480;
			
			// aapt resource value: 0x7f0900df
			public const int rlVenueItemMainContainer = 2131296479;
			
			// aapt resource value: 0x7f0900e1
			public const int rlVenueLeftImage = 2131296481;
			
			// aapt resource value: 0x7f0900e4
			public const int rlVenueMainContainer = 2131296484;
			
			// aapt resource value: 0x7f090081
			public const int rl_GameContainer = 2131296385;
			
			// aapt resource value: 0x7f090021
			public const int rl_center = 2131296289;
			
			// aapt resource value: 0x7f0900cb
			public const int rrLeftMenuAttendanceContainer = 2131296459;
			
			// aapt resource value: 0x7f0900c7
			public const int rrLeftMenuBatchAvailabiltyContainer = 2131296455;
			
			// aapt resource value: 0x7f0900c9
			public const int rrLeftMenuBatchContainer = 2131296457;
			
			// aapt resource value: 0x7f0900d1
			public const int rrLeftMenuBookingMessageContainer = 2131296465;
			
			// aapt resource value: 0x7f0900cd
			public const int rrLeftMenuEnquiryContainer = 2131296461;
			
			// aapt resource value: 0x7f0900cf
			public const int rrLeftMenuEnquiryUserContainer = 2131296463;
			
			// aapt resource value: 0x7f0900d3
			public const int rrLeftMenuInvoiceContainer = 2131296467;
			
			// aapt resource value: 0x7f0900d5
			public const int rrLeftMenuLogOutContainer = 2131296469;
			
			// aapt resource value: 0x7f0900c4
			public const int saveLoginCheckBox = 2131296452;
			
			// aapt resource value: 0x7f090061
			public const int spinnerEnquiryGame = 2131296353;
			
			// aapt resource value: 0x7f0900a1
			public const int spinnerInvoiceModeOfPayment = 2131296417;
			
			// aapt resource value: 0x7f090091
			public const int spinnerInvoiceMonth = 2131296401;
			
			// aapt resource value: 0x7f09004f
			public const int txtActionBarAppName = 2131296335;
			
			// aapt resource value: 0x7f090052
			public const int txtActionBarVenueCode = 2131296338;
			
			// aapt resource value: 0x7f090015
			public const int txtAlertDialogButton = 2131296277;
			
			// aapt resource value: 0x7f090012
			public const int txtAlertDialogHeading = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int txtAlertDialogMessage = 2131296275;
			
			// aapt resource value: 0x7f090035
			public const int txtAttendance = 2131296309;
			
			// aapt resource value: 0x7f0900cc
			public const int txtAttendanceMenu = 2131296460;
			
			// aapt resource value: 0x7f0900c8
			public const int txtBatchAvailability = 2131296456;
			
			// aapt resource value: 0x7f09002b
			public const int txtBatchCount = 2131296299;
			
			// aapt resource value: 0x7f090028
			public const int txtBatchHeader = 2131296296;
			
			// aapt resource value: 0x7f0900ca
			public const int txtBatchMenu = 2131296458;
			
			// aapt resource value: 0x7f09000a
			public const int txtBookingHeading = 2131296266;
			
			// aapt resource value: 0x7f0900d2
			public const int txtBookingMenu = 2131296466;
			
			// aapt resource value: 0x7f090066
			public const int txtCommentHeader = 2131296358;
			
			// aapt resource value: 0x7f090063
			public const int txtEnquiryComment = 2131296355;
			
			// aapt resource value: 0x7f090079
			public const int txtEnquiryFeedBack = 2131296377;
			
			// aapt resource value: 0x7f090060
			public const int txtEnquiryGame = 2131296352;
			
			// aapt resource value: 0x7f0900ce
			public const int txtEnquiryMenu = 2131296462;
			
			// aapt resource value: 0x7f09005e
			public const int txtEnquiryMobile = 2131296350;
			
			// aapt resource value: 0x7f09005c
			public const int txtEnquiryName = 2131296348;
			
			// aapt resource value: 0x7f0900d0
			public const int txtEnquiryUserMenu = 2131296464;
			
			// aapt resource value: 0x7f0900d4
			public const int txtInvoiceCollection = 2131296468;
			
			// aapt resource value: 0x7f090095
			public const int txtInvoiceDiscountAmount = 2131296405;
			
			// aapt resource value: 0x7f090096
			public const int txtInvoiceLateAmount = 2131296406;
			
			// aapt resource value: 0x7f0900a0
			public const int txtInvoiceModeOfPayment = 2131296416;
			
			// aapt resource value: 0x7f090090
			public const int txtInvoiceMonth = 2131296400;
			
			// aapt resource value: 0x7f09009c
			public const int txtInvoicePayingAmount = 2131296412;
			
			// aapt resource value: 0x7f0900a2
			public const int txtInvoiceRemarks = 2131296418;
			
			// aapt resource value: 0x7f090092
			public const int txtInvoiceTotalAmount = 2131296402;
			
			// aapt resource value: 0x7f09009b
			public const int txtInvoiceTotalPayingAmount = 2131296411;
			
			// aapt resource value: 0x7f0900b7
			public const int txtInvoiceUserAmount = 2131296439;
			
			// aapt resource value: 0x7f0900b2
			public const int txtInvoiceUserBatch = 2131296434;
			
			// aapt resource value: 0x7f0900b1
			public const int txtInvoiceUserMobile = 2131296433;
			
			// aapt resource value: 0x7f0900b4
			public const int txtInvoiceUserMobile1 = 2131296436;
			
			// aapt resource value: 0x7f0900b0
			public const int txtInvoiceUserName = 2131296432;
			
			// aapt resource value: 0x7f0900d6
			public const int txtLogOut = 2131296470;
			
			// aapt resource value: 0x7f0900bc
			public const int txtName = 2131296444;
			
			// aapt resource value: 0x7f0900c0
			public const int txtPassword = 2131296448;
			
			// aapt resource value: 0x7f09006a
			public const int txtSearchEnquiryUser = 2131296362;
			
			// aapt resource value: 0x7f0900a6
			public const int txtSearchInvoiceUser = 2131296422;
			
			// aapt resource value: 0x7f090019
			public const int txtSearchPlayers = 2131296281;
			
			// aapt resource value: 0x7f090036
			public const int txtSelectDate = 2131296310;
			
			// aapt resource value: 0x7f0900bf
			public const int txtUsername = 2131296447;
			
			// aapt resource value: 0x7f09005b
			public const int txtViewEnquiryMobile = 2131296347;
			
			// aapt resource value: 0x7f09005a
			public const int txtViewEnquiryName = 2131296346;
			
			// aapt resource value: 0x7f09008f
			public const int txtViewInvoiceBatch = 2131296399;
			
			// aapt resource value: 0x7f09008d
			public const int txtViewInvoiceMobile = 2131296397;
			
			// aapt resource value: 0x7f09008c
			public const int txtViewInvoiceName = 2131296396;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int lines = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int loginhelp_layout_weight = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int max_lines = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int user_maxlength = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddBooking = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Alert_Dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AttendanceAddPlayer = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int batch = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int batch_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BatchCountUpdatePopUp = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Batches = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int BatchPlayer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int batchplayer_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int court_item = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int CourtList = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int CustomActionBar = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int datepicker_dialog = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int EnquiryForm = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int EnquiryUser = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int enquiryuser_item = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int EnquiryUserDetail = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int enquiryuserfeedback_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int game_item = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Games = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int InvoiceCollectionDetail = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int InvoiceCollectionForm = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int InvoiceUser = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int invoiceuser_item = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int InvoiceUserHistory = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Login = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Main = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int menu_drawer = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ProgressBar = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int sport_item = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Sports = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int venue_item = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Venues = 2130903072;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070003
			public const int Close_Drawer = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int Open_Drawer = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int month_prompt = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
